apiVersion: v2
name: trickster
description: A Helm chart for Trickster by AppsCode
type: application
version: v2026.1.15
appVersion: v2.0.0
home: https://github.com/open-viz/trickster
icon: https://cdn.appscode.com/images/products/kubeops/icons/android-icon-192x192.png
sources:
- https://github.com/open-viz/trickster
maintainers:
- name: appscode
  email: support@appscode.com
